[package]
name = "advent_2018"
version = "0.1.0"
authors = ["Alice Boxhall <aboxhall@chromium.org>"]

[dependencies]
libmath = "0.2.1"
regex = "0.2"
lazy_static = "1.2.0"
chrono = "0.4.6"
multimap = "0.4.0"
cpuprofiler = "0.0.3"